dist: xenial

language: python

cache:
  pip: true
  directories:
    - $HOME/.cache/pipenv
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

env:
  - PIPENV_IGNORE_VIRTUALENVS=1


matrix:
  allow_failures:
    - python: "nightly"

install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - PIPENV_PYTHON=$TRAVIS_PYTHON_VERSION pipenv install --dev

script:
  - bash scripts/test.sh

after_script:
  - bash <(curl -s https://codecov.io/bash)

