dist: xenial  # You can try changing this to bionic if xenial doesn't work

language: python

cache:
  pip: true
  directories:
    - $HOME/.cache/pipenv

python:
  - "3.10"
  - "3.9"
  - "3.8"
  - "nightly"

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

matrix:
  allow_failures:
    - python: "nightly"

install:
  - pyenv versions  # Lists available Python versions
  - pyenv global 3.10  # Set global Python version to 3.10
  - python --version  # Confirm Python version
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv --python 3.10 install --dev  # Explicitly specify Python version for Pipenv

script:
  - python --version  # Confirm Python version again
  - pip list  # List installed packages for debugging
  - bash scripts/test.sh  # Run your test script

after_script:
  - bash <(curl -s https://codecov.io/bash)  # Post-test actions like codecov
