dist: bionic

language: python

python:
  - "3.10"
  - "3.9"
  - "3.8"
  - "nightly"

services:
  - postgresql

addons:
  postgresql: "10"  # Specify the version of PostgreSQL

cache:
  pip: true
  directories:
    - $HOME/.cache/pipenv

env:
  global:
    #- CODECOV_TOKEN=696d411a-78b6-4830-9c53-f877120b8478

  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pytest-cov
  - pip install -r requirements.txt
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev

script:
  - python --version  # Confirm Python version again
  - pip list  # List installed packages for debugging
  - bash scripts/test.sh  # Run your test script

after_script:
  - bash <(curl -s https://codecov.io/bash)  # Post-test actions like codecov
